name: Docs deploy
on:
  push:
    branches: [master]

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  docs-build:
    name: Docs build
    runs-on: ubuntu-latest
    steps:
      - name: Source code clone
        uses: actions/checkout@v3
      - name: Node.js 16 (LTS) setup
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Dependencies installation
        run: yarn ci
      - name: Coding standard check
        run: yarn lint:prod
      - name: Types integrity check
        run: yarn check:types
      - name: Source code build
        run: yarn build
      - name: Artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: byloth-vuert-docs
          path: docs/.vitepress/dist

  docs-deploy:
    name: GitHub Pages deploy
    needs: docs-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Artifact download
        uses: actions/download-artifact@v3
        with:
          name: byloth-vuert-docs

      - name: GitHub Pages setup
        uses: actions/configure-pages@v1
      - name: Artifact upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: "."

      - id: deployment
        name: GitHub Pages deployment
        uses: actions/deploy-pages@v1

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
