name: "<template:publish:core>"
on:
  workflow_call:
    inputs:
      registry-url:
        default: https://registry.npmjs.org
        required: false
        type: string

    secrets:
      AUTH_TOKEN:
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Artifact download
        uses: actions/download-artifact@v4
        with:
          name: byloth-vuert-core

      - name: Node.js 20 (LTS) setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: ${{ inputs.registry-url }}

      - if: ${{ github.event.release.prerelease == true }}
        name: Pre-release package publish
        run: npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

      - if: ${{ github.event.release.prerelease == false }}
        name: Latest package publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
